with open("memory.md", "a", encoding="utf-8") as f:
    f.write("\n\n## 8. Phase 5: Pseudo-Label Ingestion (July 16, 2026)\n\n")
    f.write("Fixed a critical architectural gap where `pseudo_labels.csv` was being generated by Kaggle but ignored during training. Updated `adding_multifold_training.ipynb` to automatically search for `pseudo_labels.csv`, load the high-confidence examples, format them with `src='pseudo'`, and merge them seamlessly into `train_master` before splitting into folds.\n")
